version: '3.4'
services:

  httpuploader:
    image: stvfccn/http-uploader
    build: .
    container_name: http_uploader
    volumes:
      - ./uploads:/home/educast_upload/uploads
    restart: always
    env_file:
      - upload_srv.env
    ports:
      - "25478:25478"